import { z } from "zod";
import type { FuncTool } from "./typings/tool.js";
import type {
  MemoryAdapter,
  MemoryRetrieveArguments,
  MemoryUpdateArguments,
} from "./typings/memory.js";

/** Tool name reserved for model-directed memory retrieval. */
export const MEMORY_RETRIEVE_TOOL_NAME = "memory.retrieve";

/** Tool name reserved for model-directed memory updates. */
export const MEMORY_UPDATE_TOOL_NAME = "memory.update";

/** System instructions used by the task-local Agent that evaluates memory updates. */
const MEMORY_UPDATE_INSTRUCTIONS = `你的任务是更新记忆。

你需要根据当前的会话上下文以及 \`memory.update()\` 工具的 \`description\` 决定调用哪些 MemoryAdapter 来更新记忆。

你需要执行 memory.update 方法并生成 \`name\` 和 \`content\` 参数：

- \`name\` 参数用于路由合适的 MemoryAdapter
- \`content\` 参数用于透传给 MemoryAdapter.update(content) 方法，因此 \`content\` 的参数结构必须按照工具描述中定义的结构生成。

你可以从以下记忆系统中进行选择：`;

/** Registry and dispatcher for Agent memory systems. */
export class Memory {
  public readonly adapters = new Map<string, MemoryAdapter>();

  /**
   * Creates a memory registry from an optional ordered adapter list.
   * @param adapters Memory adapters to register.
   */
  public constructor(adapters: MemoryAdapter[] = []) {
    for (const adapter of adapters) this.register(adapter);
  }

  /**
   * Registers one memory adapter.
   * @param adapter Adapter retrieval and update operations.
   * @returns This memory registry for fluent configuration.
   */
  public register(adapter: MemoryAdapter): this {
    const retrieveName = adapter.retrieve.name.trim();
    const updateName = adapter.update.name.trim();
    if (retrieveName === "" || updateName === "") {
      throw new Error("Memory adapter name must not be empty");
    }
    if (retrieveName !== updateName) {
      throw new Error(
        `Memory adapter retrieve name "${retrieveName}" must match update name "${updateName}"`,
      );
    }
    if (this.adapters.has(retrieveName)) {
      throw new Error(`Memory adapter "${retrieveName}" is already registered`);
    }
    this.adapters.set(retrieveName, adapter);
    return this;
  }

  /**
   * Retrieves content from a named memory adapter.
   * @param name Registered adapter name.
   * @param query Search expression selected by the model.
   * @returns Adapter-specific retrieved content.
   */
  public async retrieve(name: string, query: string): Promise<unknown> {
    return this.adapter(name).retrieve(query);
  }

  /**
   * Updates content through a named memory adapter.
   * @param name Registered adapter name.
   * @param content JSON-encoded content generated by the memory update Agent.
   * @returns Adapter-specific update result.
   */
  public async update(name: string, content: string): Promise<unknown> {
    return this.adapter(name).update(content);
  }

  /**
   * Builds the public tool used by the primary Agent to retrieve memory.
   * @returns A retrieval tool reflecting all currently registered adapters.
   */
  public retrieveTool(): FuncTool {
    const parameters = z.object({
      name: adapterNameSchema([...this.adapters.keys()]),
      query: z.string().describe("要召回的查询条件"),
    }).strict();
    const memory = this;
    const retrieve = async function retrieve(
      values: MemoryRetrieveArguments,
    ): Promise<unknown> {
      return memory.retrieve(values.name, values.query);
    };
    Object.defineProperty(retrieve, "name", { value: MEMORY_RETRIEVE_TOOL_NAME });
    return Object.assign(retrieve, {
      description: selectionDescription(
        "召回记忆，可以从以下源选择合适的进行召回：",
        [...this.adapters.values()].map(({ retrieve: operation }) => operation),
      ),
      parameters,
    });
  }

  /**
   * Builds the private tool used by a task-local Agent to update memory.
   * @returns An update tool reflecting all currently registered adapters.
   */
  public updateTool(): FuncTool {
    const parameters = z.object({
      name: adapterNameSchema([...this.adapters.keys()]),
      content: z.string().describe("透传给所选 MemoryAdapter.update(content) 的 JSON 字符串"),
    }).strict();
    const memory = this;
    const update = async function update(
      values: MemoryUpdateArguments,
    ): Promise<unknown> {
      return memory.update(values.name, values.content);
    };
    Object.defineProperty(update, "name", { value: MEMORY_UPDATE_TOOL_NAME });
    return Object.assign(update, {
      description: selectionDescription(
        "更新记忆，可以从以下源选择合适的进行更新：",
        [...this.adapters.values()].map(({ update: operation }) => operation),
      ),
      parameters,
    });
  }

  /**
   * Builds the complete system prompt for the memory update Agent.
   * @returns Instructions containing every registered update operation description.
   */
  public updateInstructions(): string {
    return `${MEMORY_UPDATE_INSTRUCTIONS}\n\n${selectionList(
      [...this.adapters.values()].map(({ update }) => update),
    )}\n\n一旦完成任务立即退出。`;
  }

  /**
   * Resolves a registered adapter by name.
   * @param name Adapter name selected by the model.
   * @returns Matching memory adapter.
   */
  private adapter(name: string): MemoryAdapter {
    const adapter = this.adapters.get(name);
    if (adapter === undefined) throw new Error(`Unknown memory adapter "${name}"`);
    return adapter;
  }
}

/**
 * Creates the JSON-schema-compatible adapter selector used by memory tools.
 * @param names Registered adapter names in declaration order.
 * @returns Zod enum, including an unsatisfiable schema for an empty registry.
 */
function adapterNameSchema(names: string[]): z.ZodEnum<Record<string, string>> {
  return z.enum(names).describe("记忆源的名称");
}

/**
 * Formats a model-facing tool description with adapter selection guidance.
 * @param prefix Purpose of the memory tool.
 * @param operations Adapter operations advertised by the tool.
 * @returns Complete tool description.
 */
function selectionDescription(
  prefix: string,
  operations: Array<Pick<Function, "name"> & { description: string }>,
): string {
  const choices = selectionList(operations);
  return choices === "" ? prefix : `${prefix}\n${choices}`;
}

/**
 * Formats operation metadata as the adapter list expected by model prompts.
 * @param operations Adapter operations to describe.
 * @returns Newline-separated adapter choices.
 */
function selectionList(
  operations: Array<Pick<Function, "name"> & { description: string }>,
): string {
  return operations
    .map(({ name, description }) => `- name: ${name}\n  description: ${description}`)
    .join("\n");
}
