import type { InputItem } from "@maozy13/neuralink";

/** Role of user-visible text, image, and file conversation items. */
export type ConversationRole = "user" | "assistant";

/** Metadata generated locally for every retained conversation item. */
export interface ConversationItemMetadata {
  /** Locally generated stable UUID. */
  id: string;
  /** Local creation time as a Unix timestamp in milliseconds. */
  created_at: number;
}

/** Text stored in a conversation. */
export interface TextConversationItem extends ConversationItemMetadata {
  /** Stable item discriminator. */
  type: "text";
  /** Item producer. */
  role: ConversationRole;
  /** Plain text content. */
  text: string;
}

/** Image stored in a conversation. */
export interface ImageConversationItem extends ConversationItemMetadata {
  /** Stable item discriminator. */
  type: "image";
  /** Item producer. */
  role: ConversationRole;
  /** Image URI. */
  image: string;
}

/** File stored in a conversation. */
export interface FileConversationItem extends ConversationItemMetadata {
  /** Stable item discriminator. */
  type: "file";
  /** Item producer. */
  role: ConversationRole;
  /** File URI. */
  file: string;
}

/** Model reasoning stored for inspection but not replayed to NeuralLink. */
export interface ReasoningConversationItem extends ConversationItemMetadata {
  /** Stable item discriminator. */
  type: "reasoning";
  /** Item producer. */
  role: "assistant";
  /** Reasoning body. */
  content: string;
  /** Reasoning summary. */
  summary: string;
}

/** Function call selected by the model. */
export interface FunctionCallConversationItem extends ConversationItemMetadata {
  /** Stable item discriminator. */
  type: "function_call";
  /** Item producer. */
  role: "assistant";
  /** Function-call identifier. */
  call_id: string;
  /** Registered function name. */
  name: string;
  /** JSON-encoded arguments. */
  arguments: string;
}

/** Result returned by a local tool. */
export interface FunctionCallOutputConversationItem extends ConversationItemMetadata {
  /** Stable item discriminator. */
  type: "function_call_output";
  /** Item producer. */
  role: "tool";
  /** Associated function-call identifier. */
  call_id: string;
  /** Serialized tool result. */
  output: string;
}

/** Free-form custom tool call selected by the model. */
export interface CustomToolCallConversationItem extends ConversationItemMetadata {
  /** Stable item discriminator. */
  type: "custom_tool_call";
  /** Item producer. */
  role: "assistant";
  /** Custom-tool call identifier. */
  call_id: string;
  /** Registered custom tool name. */
  name: string;
  /** Free-form tool input generated by the model. */
  input: string;
}

/** Result returned by a local custom tool. */
export interface CustomToolCallOutputConversationItem extends ConversationItemMetadata {
  /** Stable item discriminator. */
  type: "custom_tool_call_output";
  /** Item producer. */
  role: "tool";
  /** Associated custom-tool call identifier. */
  call_id: string;
  /** Serialized custom-tool result. */
  output: string;
}

/** Any item retained by a WallE conversation. */
export type ConversationItem =
  | TextConversationItem
  | ImageConversationItem
  | FileConversationItem
  | ReasoningConversationItem
  | FunctionCallConversationItem
  | FunctionCallOutputConversationItem
  | CustomToolCallConversationItem
  | CustomToolCallOutputConversationItem;

/**
 * Removes locally generated metadata from each member of a conversation-item union.
 * @template Item Conversation item union to transform.
 */
type WithoutConversationItemMetadata<Item> = Item extends ConversationItemMetadata
  ? Omit<Item, keyof ConversationItemMetadata>
  : never;

/** Item accepted for insertion, with local metadata optionally supplied by the caller. */
export type ConversationItemInput =
  | ConversationItem
  | WithoutConversationItemMetadata<ConversationItem>;

/** NeuralLink-compatible representation returned by a conversation. */
export type ConversationInput = InputItem[];
